// <auto-generated />
namespace Website_Ban_Nuoc_Online_New.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class InitWebsite : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitWebsite));
        
        string IMigrationMetadata.Id
        {
            get { return "202512051801033_InitWebsite"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
